server:
  port: 3344
spring:
  application:
    name: cloud-config-server-3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liqiong888/cloudConfig.git
          search-paths:
            - cloudConfig
          label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  #将自己注册进eureka
  register-with-eureka: true
  #  抓取注册中心
  fetch-registry: true