server:
  port: 8003
spring:
  application:
    name: stream-consumer-input
  cloud:
    stream:
      binders: #此处设置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称 用于rabbitmq的整合
          type: rabbit #消息组件你设置
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: 39.105.136.137
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名字是通道的名称
          destination: studyExchange #表示要使用的Exchange名称定义
          content-type: application/json #设置消息类型，本次为json 文本设置为 text/plain
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: mycloud

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  #将自己注册进eureka
  register-with-eureka: true
  #  抓取注册中心
  fetch-registry: true
  instance:
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔（默认是90s）
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔
    instance-id: receive-8003.com #在信息列表中显示主机的名称
    prefer-ip-address: true  #访问的路径变为IP