server:
  port: 80
spring:
  application:
    name: consumer-server-eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,
  #将自己注册进eureka
  register-with-eureka: true
  #  抓取注册中心
  fetch-registry: true
