server:
  port: 8006
spring:
  application:
    name: provider-server-consul
management:
  server:
    port: 4452
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
#        instance-id: provider-consul-service-id
        service-name: ${spring.application.name}
#        health-check-path: ${management.server.servlet.context-path}/health
#        health-check-interval: 15s
