server:
  port: 3344
spring:
  application:
    name: cloud-config-server-9001
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liqiong888/mycloud/blob/master/cloud-config/config.yml
          default-label: master
          search-paths:
          - mycloud/blob/master/cloud-config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  #将自己注册进eureka
  register-with-eureka: true
  #  抓取注册中心
  fetch-registry: true